### ISSUE TITLE
Windows 11 Pro is displayed as Windows 10 Pro (2009)

### ISSUE THREAD

**Issue by Flat** [Macchina-CLI/libmacchina#76]
**Describe the bug**
Macchina incorrectly states the Operating system on Windows 11

**To Reproduce**
1. Install Windows 11
2. run `macchina`
3. ???
4. Windows 10

**Expected behavior**
This should detect Windows 11 Pro as the current operating system.

**Screenshots**
![image](https://user-images.githubusercontent.com/2048861/136114962-702a9795-da60-4bd6-987c-9bcc1425510d.png)

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Windows 11
 - Desktop Environment dwm.exe
 - Operating System Windows NT/Windows 11
 - Terminal Microsoft Terminal
 - Macchina's version 1.1.7

**Comment by FantasyTeddy** [comment]
Now that Windows 11 is out for a few weeks, searching for this problem seems to reveal that they probably won't change the values in this registry entry (for whatever strange reasons that might be).

One suggestion that came up [in a discussion](https://docs.microsoft.com/en-us/answers/questions/555857/windows-11-product-name-in-registry.html), was to use WMI to retrieve this information: [Win32_OperatingSystem](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-operatingsystem).Caption

Do you think this would be a valid change to use WMI instead of the Registry to get this information?

**Comment by grtcdr** [comment]
I don't see why not, you can submit a PR if you'd like.

**Comment by FantasyTeddy** [comment]
Okay I will give it a shot. Do we want to keep the `ReleaseId` in parenthesis after the `ProductName`? It seems like this is also an outdated registry entry.

**Comment by grtcdr** [comment]
Yeah, I don't think the `ReleaseId` is that important to have.

**Comment by FantasyTeddy** [comment]
Great I will most likely omit it then.
Before I do any work I'm going to wait if #95 will require some changes, because it would simplify anything I do here.

**Comment by grtcdr** [comment]
Sounds good :)
