### ISSUE TITLE
Confusion about readouts

### ISSUE THREAD

**Issue by FantasyTeddy** [Macchina-CLI/libmacchina#95]
While working on a solution for #76, I stumbled across the `ProductReadout`.
This readout seems to be unused in *macchina* but according to its documentation (and implementation for Linux) this should report some information about the **machine** that is being used. However the Windows version of this readout reports back **operating system** information.

Could you clarify which one is correct?

Additionally I was wondering whether the `os_release()` function from `KernelReadout` should maybe report the full version number (10.0.19043) instead of just the build number (19043) in Windows.

**Comment by grtcdr** [comment]
We should be reporting product information, i.e. your computer's make and model, in the `ProductReadout`. I'm not sure why we're not doing this, but I'd ask @123marvin123 before proceeding.

I don't think the full version number is necessary, most people worry about the version (10, 11) and the build number, as far as I know.

**Comment by 123marvin123** [comment]
It's possible that I misunderstood the term "product" while implementing the windows support as which windows edition is being used (e.g. "Windows Server"). We can change the readout for windows, so it is in line with the other implementations.

Sadly, I don't have a (usable) windows machine anymore, but it shouldn't be too hard since this Information, will most likely be somewhere in the registry.

**Comment by 123marvin123** [comment]
> I think the confusion might come from the [documentation of the `ProductReadout`](https://docs.rs/libmacchina/3.8.6/libmacchina/traits/trait.ProductReadout.html) which states "[...] used for getting _product information_ about the **hosts operating system**." If that's okay I will give it a try to report the correct information for Windows and maybe change the documentation to be more clear.
> 
> > I don't think the full version number is necessary, most people worry about the version (10, 11) and the build number, as far as I know.
> 
> Okay I can live with that :)

You’re right, the example code and the written explanation at the bottom is actually contradicting.

**Comment by FantasyTeddy** [comment]
Now that I took a closer look I realized that the macOS implementation behaves the same as Windows and reports operating system information instead of device information.

Maybe we should also simplify the trait a little bit: `vendor()` & `family()` totally make sense, but the other three are not entirely clear to me:
- `version()`: What kind of version do we report? This makes sense for OS information, but I don't think it is too useful for device information.
- `name()`: Is this the name of the product? If so, how is it different than `product()`?
- `product()`: see `name()`

Can we maybe merge those three functions into one single function?

**Comment by grtcdr** [comment]
I think we should keep them separate, they don't have to be implemented for operating systems that don't split them up.

The reason all of those exist is simply because product information on Linux exists on multiple different files, it's fragmented, and I hate it. But, we designed the trait with this in mind. Probably because Linux was the first platform that macchina supported.

Hardware manufacturers are really really lazy, and this shows when you look inside the different `product_*` files in `/sys/class/dmi/id/`, some files have the same text as others, others have some incoherent shit, and others contain "To be filled by O.E.M.". We are fighting this with some tricks that we apply when we process these different files (such as only retaining uniques, looking for and replacing placeholder text, etc.)

We *should* to keep them separate, but if a redesign were to take place (which I'm not against, it's just a tedious chore), we have to intelligently handle these weird cases.

**Comment by grtcdr** [comment]
Actually, we should work to make this simpler, so yes, we *SHOULD* group them, as you suggested.

**Comment by grtcdr** [comment]
Here's how fragmented product information is on Linux:

![2021-11-13T21:31:25,696838751+01:00](https://user-images.githubusercontent.com/35816711/141658216-c234d9d9-e18c-44ff-a4c4-101c9199b35d.png)

This wouldn't suck, of course, if every OEM made sure that every file contained the appropriate information.

**Comment by FantasyTeddy** [comment]
> Actually, we should work to make this simpler, so yes, we _SHOULD_ group them, as you suggested.

I would suggest to keep `product()` and remove `version()` & `name()`.

As for how to do this for all the different platforms, this would be my plan:
- Android: Only `version()` is being used and can be replaced by `product()`.
- FreeBSD: Not implemented anyways.
- Linux: I would suggest using `/sys/class/dmi/id/product_name` for the `ProductReadout::product()` and keep the logic in `GeneralReadout::machine()` mostly the same (the `version` will need to be fetched separately).
- macOS: Since this reports OS information anyways, this needs to be rewritten entirely.
- NetBSD: I would switch `product()` to `family()` and `version()` to `product()`.
- Windows: Same as macOS where this needs to be rewritten anyways.
